### ISSUE TITLE
Rule mb_str_func produces issues when used in download context

### ISSUE THREAD

**Issue by emri99** [Coffreo/php-cs-fixer-config#9]
Using risky rule `mb_str_func` raises issues when calculating binary data size.

This leads to downloaded file being invalid when used in `Content-Length` header.

Proposition is to remove this risky rule.

A temporary fix can be to add theses lines into `.php_cs` file before return

```php
$config->setRules(array_merge($config->getRules(),
    // disable mb_str_functions as it replace strlen with mb_strlen
    // which breaks the binary content length calculation
    // causing returned response to be invalid
    ['mb_str_functions' => false]
));

return $config;
```

@jeremiegrenier an opinion about this ?

**Comment by jeremiegrenier** [comment]
If the rules break normal behavior, we must remove it.
